version: "3.3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: Diango
    restart: always
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$DBPassProd
    depends_on:
      - db

volumes:
  db_data:
